---
refresh_interval: 0 # seconds
max_price: 550 # dollars/euros/etc
urls:
  - https://www.amazon.com/gp/product/B08WGTL4CW#aod
  - https://www.amazon.com/gp/product/B08FC5L3RG#aod
  - https://www.amazon.com/gp/product/B08NYP7KG6#aod
  - https://www.amazon.com/gp/product/B08FC6MR62#aod
...
