---
refresh_interval: 2 # seconds
urls:
  - https://www.microcenter.com/product/628685/asus-geforce-rtx-3090-strix-overclocked-triple-fan-24gb-gddr6x-pcie-40-graphics-card 
  - https://www.microcenter.com/product/628321/asus-geforce-rtx-3090-tuf-gaming-overclocked-triple-fan-24gb-gddr6x-pcie-40-graphics-card
  - https://www.microcenter.com/product/628738/evga-geforce-rtx-3090-ftw3-ultra-triple-fan-24gb-gddr6x-pcie-40-graphics-card
  - https://www.microcenter.com/product/631999/asus-nvidia-geforce-rtx-3090-rog-strix-white-overclocked-triple-fan-24gb-gddr6x-pcie-40-graphics-card
  - https://www.microcenter.com/product/628320/msi-geforce-rtx-3090-gaming-x-trio-triple-fan-24gb-gddr6x-pcie-40-graphics-card
  - https://www.microcenter.com/product/631534/msi-geforce-rtx-3090-suprim-x-overclocked-triple-fan-24gb-gddr6x-pcie-40-graphics-card
  - https://www.microcenter.com/product/631675/gigabyte-geforce-rtx-3090-aorus-master-overclocked-triple-fan-24gb-gddr6x-pcie-40-graphics-card
  - https://www.microcenter.com/product/628413/gigabyte-geforce-rtx-3090-gaming-overclocked-triple-fan-24gb-gddr6x-pcie-40-graphics-card
  - https://www.microcenter.com/product/628740/evga-geforce-rtx-3090-xc3-ultra-gaming-overclocked-triple-fan-24gb-gddr6x-pcie-40-graphics-card
  - https://www.microcenter.com/product/628326/msi-geforce-rtx-3090-ventus-3x-overclocked-triple-fan-24gb-gddr6x-pcie-40-graphics-card
  - https://www.newegg.com/gigabyte-geforce-rtx-3090-gv-n3090aorusx-wb-24gd/p/N82E16814932386?quicklink=true
  - https://www.newegg.com/gigabyte-geforce-rtx-3090-gv-n3090vision-oc-24gd/p/N82E16814932365?quicklink=true
  - https://www.newegg.com/asus-geforce-rtx-3090-rog-strix-rtx3090-o24g-white/p/N82E16814126482?quicklink=true
  - https://www.newegg.com/gigabyte-geforce-rtx-3090-gv-n3090aorus-x-24gd/p/N82E16814932340?quicklink=true
  - https://www.newegg.com/asus-geforce-rtx-3090-rog-strix-rtx3090-o24g-gaming/p/N82E16814126456
  - https://www.newegg.com/evga-geforce-rtx-3090-24g-p5-3987-kr/p/N82E16814487526
  - https://www.newegg.com/asus-geforce-rtx-3090-tuf-rtx3090-24g-gaming/p/N82E16814126455
  - https://www.newegg.com/msi-geforce-rtx-3090-rtx-3090-gaming-x-trio-24g/p/N82E16814137595
  - https://www.newegg.com/msi-geforce-rtx-3090-rtx3090-suprim-x-24g/p/N82E16814137610
  - https://www.newegg.com/gigabyte-geforce-rtx-3090-gv-n3090eagle-oc-24gd/p/N82E16814932328
  - https://www.newegg.com/evga-geforce-rtx-3090-24g-p5-3985-kr/p/N82E16814487525
  - https://www.newegg.com/evga-geforce-rtx-3090-24g-p5-3975-kr/p/N82E16814487524
  - https://www.newegg.com/gigabyte-geforce-rtx-3090-gv-n3090gaming-oc-24gd/p/N82E16814932327
  - https://www.newegg.com/gigabyte-geforce-rtx-3090-gv-n3090aorusx-w-24gd/p/N82E16814932387
  - https://www.newegg.com/msi-geforce-rtx-3090-rtx-3090-ventus-3x-24g-oc/p/N82E16814137596
  - https://www.newegg.com/msi-geforce-rtx-3090-rtx-3090-ventus-3x-24g/p/N82E16814137599
  - https://www.newegg.com/gigabyte-geforce-rtx-3090-gv-n3090eagle-24gd/p/N82E16814932366
  - https://www.newegg.com/gigabyte-geforce-rtx-3090-gv-n3090aorus-m-24gd/p/N82E16814932341
  - https://www.newegg.com/pny-geforce-rtx-3090-vcg309024tfxppb/p/N82E16814133807
  - https://www.newegg.com/msi-geforce-rtx-3090-rtx-3090-suprim-24g/p/N82E16814137635
  - https://www.amazon.com/EVGA-GeForce-Technology-Backplate-24G-P5-3987-KR/dp/B08J5F3G18/ref=sr_1_1?crid=FRM0WP9EX5DD&dchild=1&keywords=rtx+3090&qid=1617312067&sprefix=rtx+3090%2Caps%2C177&sr=8-1
  - https://www.amazon.com/PNY-GeForce-3090-24GB-XLR8/dp/B08HBVX53D/ref=sr_1_2?crid=FRM0WP9EX5DD&dchild=1&keywords=rtx+3090&qid=1617312067&sprefix=rtx+3090%2Caps%2C177&sr=8-2
  - https://www.amazon.com/EVGA-24G-P5-3998-KR-RTX-3090-Kingpin/dp/B08SWLJVS9/ref=sr_1_6?crid=FRM0WP9EX5DD&dchild=1&keywords=rtx+3090&qid=1617312067&sprefix=rtx+3090%2Caps%2C177&sr=8-6
  - https://www.amazon.com/ZOTAC-Graphics-IceStorm-Advanced-ZT-A30900J-10P/dp/B08ZL6XD9H/ref=sr_1_17?crid=FRM0WP9EX5DD&dchild=1&keywords=rtx+3090&qid=1617312067&sprefix=rtx+3090%2Caps%2C177&sr=8-17
  - https://www.amazon.com/ZOTAC-Graphics-IceStorm-Advanced-ZT-A30900D-10P/dp/B08HJQ182D/ref=sr_1_18?crid=FRM0WP9EX5DD&dchild=1&keywords=rtx+3090&qid=1617312067&sprefix=rtx+3090%2Caps%2C177&sr=8-18
  - https://www.amazon.com/ASUS-GeForce-Graphics-DisplayPort-Bearings/dp/B08HJGNJ81/ref=sr_1_19?crid=FRM0WP9EX5DD&dchild=1&keywords=rtx+3090&qid=1617312126&sprefix=rtx+3090%2Caps%2C177&sr=8-19
  - https://www.amazon.com/NVIDIA-RTX-3090-Founders-Graphics/dp/B08HR6ZBYJ/ref=sr_1_20?crid=FRM0WP9EX5DD&dchild=1&keywords=rtx+3090&qid=1617312126&sprefix=rtx+3090%2Caps%2C177&sr=8-20
  - https://www.bhphotovideo.com/c/product/1595781-REG/pny_technologies_vcg309024tfxmpb_geforce_rtx_3090_24gb.html
  - https://www.bhphotovideo.com/c/product/1606697-REG/gigabyte_gv_n3090aorus_m_24gd_aorus_geforce_rtx_3090.html
  - https://www.bhphotovideo.com/c/product/1605889-REG/msi_geforce_rtx_3090_suprim.html
  - https://www.bhphotovideo.com/c/product/1607043-REG/asus_rtx3090_24g_ek_geforce_rtx_3090_24g.html
  - https://www.bhphotovideo.com/c/product/1622297-REG/zotac_zt_a30900j_10p_gaming_geforce_rtx_3090.html
  - https://www.bhphotovideo.com/c/product/1601764-REG/asus_rog_strix_rtx3090_o24g_gaming_rog_strix_geforce_rtx.html
  - https://www.bhphotovideo.com/c/product/1614302-REG/asus_rog_strix_rtx3090_o24g_white_rog_strix_geforce_rtx.html
  - https://www.samsclub.com/p/pny-geforce-rtx3090-24gb-graphics-card/prod25090931
  - https://www.samsclub.com/p/pny-geforce-rtx3090-24gb-graphics-card/prod25090932
  - https://www.microcenter.com/product/630283/amd-ryzen-9-5900x-vermeer-37ghz-12-core-am4-boxed-processor
  - https://www.newegg.com/amd-ryzen-9-5900x/p/N82E16819113664?Description=ryzen%209%205900x&cm_re=ryzen_9%205900x-_-19-113-664-_-Product
  - https://www.amazon.com/AMD-Ryzen-5900X-24-Thread-Processor/dp/B08164VTWH/ref=sr_1_3?dchild=1&keywords=ryzen+9+5900x&qid=1617312183&sr=8-3
  - https://www.bhphotovideo.com/c/product/1598373-REG/amd_100_100000061wof_ryzen_9_5900x_3_7.html
  - https://www.newegg.com/asrock-radeon-rx-6800-xt-rx-6800-xt-16g/p/N82E16814930045
  - https://www.newegg.com/asus-radeon-rx-6800-xt-rx6800xt-16g/p/N82E16814126472
  - https://www.newegg.com/gigabyte-radeon-rx-6800-xt-gv-r68xt-16gc-b/p/N82E16814932373
  - https://www.newegg.com/msi-radeon-rx-6800-xt-rx-6800-xt-16g/p/N82E16814137607
  - https://www.newegg.com/sapphire-radeon-rx-6800-xt-21304-01-20g/p/N82E16814202388
...
